In [2]:
import pandas as pd

In [3]:
# Load the hotels JSON file into a DataFrame 
df = pd.read_json("../../Extract/hotels/data/hotels_descriptions.json")
df.head()

,location,name,rating,url,description,coordinates
0,Rouen,Sous les Etoiles - dans le plus haut gratte-ci...,"9,2",https://www.booking.com/hotel/fr/sous-les-etoi...,L’hébergement Sous les Etoiles - dans le plus ...,"49.4400384,1.0856876"
1,Rouen,L'Oasis Rouennais - Hypercentre - Gare rive Ga...,10,https://www.booking.com/hotel/fr/oasis-rouenna...,L’hébergement L'Oasis Rouennais - Hypercentre ...,"49.4480098,1.0955547"
2,Rouen,"Radisson Blu Hotel, Rouen Centre","8,9",https://www.booking.com/hotel/fr/radisson-blu-...,"L’établissement Radisson Blu Hotel, Rouen Cent...","49.446441,1.09412"
3,Paris,Studio à Montmartre,"8,0",https://www.booking.com/hotel/fr/studio-a-mont...,"Offrant une vue sur le jardin, l’hébergement S...","48.8915065,2.3385854999999998"
4,Paris,Apartment Cosy 3P Quartier République,None,https://www.booking.com/hotel/fr/apartment-cos...,"Doté d’une connexion Wi-Fi gratuite, l’héberge...","48.8681307,2.3586776"

In [4]:
# Inspect the list of unique cities in the dataset 
print(df["location"].unique())

['Rouen' 'Paris' 'Le Mont-Saint-Michel' 'Chateau du Haut Koenigsbourg'
 'Dijon' 'Annecy' 'Besancon' 'Eguisheim' 'Grenoble' 'Colmar' 'Strasbourg'
 'Lille' 'Le Havre' 'Saint-Malo' 'Amiens' 'Bayeux' 'Gorges du Verdon'
 'Bormes les Mimosas' 'Cassis' 'Uzes' 'N%C3%AEmes' 'Aigues Mortes'
 'Carcassonne' 'Montauban' 'Toulouse' 'Ariege' 'Collioure' 'Marseille'
 'Aix en Provence' 'Saintes Maries de la mer' 'Avignon' 'Lyon' 'Bayonne'
 'Biarritz' 'La Rochelle']

In [5]:
# Count the number of hotels per city 
nbr_hotels_cities = df.groupby("location").count()
nbr_hotels_cities

                              name  rating  url  description  coordinates
location
Aigues Mortes                   25      25   25           25           25
Aix en Provence                 25      23   25           25           25
Amiens                          25      25   25           25           25
Annecy                          25      25   25           25           25
Ariege                          25      23   25           25           25
Avignon                         25      25   25           25           25
Bayeux                          25      25   25           25           25
Bayonne                         25      25   25           25           25
Besancon                        25      25   25           25           25
Biarritz                        25      25   25           25           25
Bormes les Mimosas              25      24   25           25           25
Carcassonne                     25      25   25           25           25
Cassis                          25      24   25           25           25
Chateau du Haut Koenigsbourg    25      24   25           25           25
Collioure                       25      25   25           25           25
Colmar                          25      25   25           25           25
Dijon                           25      24   25           25           25
Eguisheim                       25      25   25           25           25
Gorges du Verdon                25      25   25           25           25
Grenoble                        25      25   25           25           25
La Rochelle                     25      24   25           25           25
Le Havre                        25      25   25           25           25
Le Mont-Saint-Michel            25      25   25           25           25
Lille                           25      25   25           25           25
Lyon                            25      23   25           25           25
Marseille                       25      25   25           25           25
Montauban                       25      25   25           24           25
N%C3%AEmes                      25      25   25           25           25
Paris                           25      19   25           25           25
Rouen                           25      25   25           25           25
Saint-Malo                      25      25   25           25           25
Saintes Maries de la mer        25      24   25           25           25
Strasbourg                      25      25   25           25           25
Toulouse                        25      25   25           25           25
Uzes                            25      25   25           25           25

In [6]:
df.shape

(875, 6)